### ISSUE TITLE
Improve Data Importer

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/analyzedphenotypes#116]
1. Make file re-upload option available only when validation fails.
![image](https://user-images.githubusercontent.com/15472253/69644432-432e4c80-102a-11ea-924c-876349ad40ae.png)

2. Automatically select genus corresponding to the project.
![image](https://user-images.githubusercontent.com/15472253/69644693-9902f480-102a-11ea-80a0-798d56474000.png)

3. Disable Import Button.
![image](https://user-images.githubusercontent.com/15472253/69644757-b041e200-102a-11ea-9e97-b48dd15a754d.png)

4. Apply margin/padding/spacing around buttom.
![image](https://user-images.githubusercontent.com/15472253/69645519-e9c71d00-102b-11ea-8232-b019e41e8a1a.png)

Fix warning and error.
1. On fresh install and genus not configured.
![image](https://user-images.githubusercontent.com/15472253/69645589-04999180-102c-11ea-9072-c5a0912f4e9a.png)

2. Not validating unit to data type and when data file is empty (just contains column headers).

**Comment by laceysanderson** [comment]
Merged
