### ISSUE TITLE
Improve Trait Importer, Data Download and Documentation

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/analyzedphenotypes#118]
1. Data download fails when export file type is set to xlsx. This is because it could not locate the required library. Implement a library check during install to ensure that this library gets installed first before the module.

2. Trait Importer does not support tsv file.
![image](https://user-images.githubusercontent.com/15472253/69755224-62f26d00-111d-11ea-90a7-e1ddeb4416a7.png)

3. Add a check in trait importer to exclude empty row.

4. Fix typographical errors in the documentation.

**Comment by laceysanderson** [comment]
PR Merged
