### ISSUE TITLE
Cannot upload "stand-alone" phenotypes (without pre-existing) germplasm in db

### ISSUE THREAD

**Issue by elor77** [UofS-Pulse-Binfo/analyzedphenotypes#120]
Hi @laceysanderson 

We're in the process of learning these tools so we went ahead and created a sample site based on TRIPAL tutorial. 

We've successfully (i think) installed analyzed phenotypes. However once I tried to upload the file (formatted as specified) we received error that the germplasm in question did not exist.

I went ahead and installed `tripal_germplasm_importer`
When trying to upload my germplasm file I get the following error
`ERROR: The genus, Citrus, species, sinensis, has no matched organism in chado.organism.`

I already created this organism and veryfied it's existence in the db (chado.organism table) so I'm not sure what this error means

I opened this issue under the `tripal_germplasm_importer` but i'm not sure that page it is very active..
I'm trying to follow your documentation (which is great, by the way) as best I can but maybe we're missing something basic?

Thanks in advance
Elad

**Comment by laceysanderson** [comment]
For our reference, the issue referred to is here: https://github.com/UofS-Pulse-Binfo/tripal_germplasm_importer/issues/21 

I've commented on your other issue regarding importing germplasm. We'll get the problem sorted out over there.

> We've successfully (i think) installed analyzed phenotypes. However once I tried to upload the file (formatted as specified) we received error that the germplasm in question did not exist.

It sounds like our documentation could use a warning lettings users know that germplasm must already exist. This was done to ensure proper meta-data for the germplasm.
