### ISSUE TITLE
Error when trying to display distribution chart

### ISSUE THREAD

**Issue by elor77** [UofS-Pulse-Binfo/analyzedphenotypes#121]
@laceysanderson 
Managed to load the phenotype file, and it downloads correctly. 
However, when trying to display the distribution plot I get the following tripald3 error:
`Error: Call to undefined function tripald3_load_libraries() in analyzedphenotypes_traitplot_form() (line 402 of /var/www/html/sites/all/modules/analyzedphenotypes/includes/analyzedphenotypes.traitplot.page.inc).`

**Comment by laceysanderson** [comment]
That implies you don't have Tripal D3 (https://github.com/tripal/tripald3) installed. You must have downloaded the module (analyzedphenotypes) before I made the fix regarding dependencies. Installing TripalD3 including downloading the [D3v3](https://github.com/d3/d3/releases?after=v4.0.0) library should fix this issue. Heads up: there's a weird issue with the Drupal libraries module (dependency of TripalD3) which requires it to be enabled separately and before Tripal D3.

**Comment by elor77** [comment]
Just to make sure I understand correctly:
1. Download and enable https://github.com/d3/d3/tree/v3.5.17
2. Repeat for https://github.com/tripal/tripald3
?

**Comment by laceysanderson** [comment]
@elor77,

1. Download https://github.com/d3/d3/tree/v3.5.17 and unpack in [drupal site]/sites/all/libraries/d3. This is a library so it doesn't need to be enabled.
2. Download and enable https://www.drupal.org/project/libraries/releases/7.x-2.5
3. Download and enable https://github.com/tripal/tripald3
Make sure to enable the libraries module independently and before Tripal D3

**Comment by elor77** [comment]
@laceysanderson 
Works perfectly!!! Thank you..
Is there a way to choose different X-axis?
And also - how do I cite you guys?

![image](https://user-images.githubusercontent.com/44900229/77247452-ff46ff00-6c39-11ea-8bd9-444436a393d5.png)

**Comment by laceysanderson** [comment]
I @elor77 unfortunately not though we are working on making the automatic choice for axis boundaries better.

As for as citation, I've added that to the readme:
> Sanderson, L.A., Tan R. (2020). Analyyzed Phenotypes: Tripal support for analyzed phenotypic data including data loaders, exporters, trait pages and summaries on germplasm pages. DEVELOPMENT VERSION. University of Saskatchewan, Pulse Crop Research Group, Saskatoon, SK, Canada.
