### ISSUE TITLE
Trait Distribution Chart

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/analyzedphenotypes#2]
I'm noticing a number of peculiarities in the Beanplots:
1. The mean associated with a bar (shown on hover over) doesn't match the y-axis value.
2. There is a single bar per mean value --these should be binned appropriately. For example, currently there are separate bars for means of 78, 78.1333, 78.4667, 78.6667, etc. These should all be within a single bar. I would use the height of the bar in reference to the y-axis to determine how big your bins need to be (for example, one bin per minor tick.
3. The number of minor ticks is out of control ;-) Currently there seems to be a minor tick per data point resulting in a solid black y-axis. Instead there should be a set number of evenly distributed minor ticks. For example, in the screenshot below where major ticks are every 5 units, it would be good to have minor ticks every 1 unit (as it is between 50 and 55). The key is to have the same number of minor ticks between every major tick pair regardless of the data shown.
![screen shot 2017-07-10 at 11 04 42 am](https://user-images.githubusercontent.com/1566301/28030378-cc708232-6560-11e7-85df-78106237221e.png)

NOTE: The newest version of the generate tripal data module will generate data following our schema and thus can be used to test this functionality. I suggest using a generic tripal3 site to test this rather then testing on a KnowPulse clone.

**Comment by laceysanderson** [comment]
Quick Fixes from @reynoldtan for the above issues:
```diff
diff --git a/include/analyzedphenotypes.beanplot.page.inc b/include/analyzedphenotypes.beanplot.page.inc
index 2e79889..4f8ac9b 100644
--- a/include/analyzedphenotypes.beanplot.page.inc
+++ b/include/analyzedphenotypes.beanplot.page.inc
@@ -272,7 +272,8 @@ function analyzedphenotypes_beanplot_json($project_id, $trait_id) {
     array(':project_id' => $project_id, 'trait_id' => $trait_id));
   foreach($resource as $r) {
 
-    $index = $r->location . '-' . $r->year . '-' . $r->mean;
+    $mean = floor($r->mean);
+    $index = $r->location . '-' . $r->year . '-' . $mean;
 
     // If index is found, increment the number of times it appeard in the dataset.
     if (isset($results[$index])) {
@@ -281,7 +282,7 @@ function analyzedphenotypes_beanplot_json($project_id, $trait_id) {
     // Otherwise initialize the data point.
     else {
 
-      $mean = strstr($r->mean, '.') ? (float)$r->mean : (int)$r->mean;
+      //$mean = strstr($r->mean, '.') ? (float)$r->mean : (int)$r->mean;
 
       $results[$index] = array(
         'location' => $r->location,

diff --git a/include/js/beanplot.chart.js b/include/js/beanplot.chart.js
index 8ebc1c8..2f0a958 100644
--- a/include/js/beanplot.chart.js
+++ b/include/js/beanplot.chart.js
@@ -162,6 +162,7 @@
           }
 
           // Add the mean values with decimal places.
+          ticksMajor = ticksAll;
           ticksAll = ticksAll.concat(decimalVal);
           ticksNo = ticksAll.length;
 
@@ -210,7 +211,23 @@
           // Indent such tick marks.
           d3.selectAll('#bp-y-scale line')
             .attr('x2', function(d) {
-              return (d % ticksDiff == 0) ? -12 : -6;
+              //return (d % ticksDiff == 0) ? -12 : -6;
+
+              var j;
+
+              if (d % ticksDiff == 0) {
+                j = -12;
+              }
+              else {
+                if (Number.isInteger(d)) {
+                  j = -6;
+                }
+                else {
+                  j = 0;
+                }
+              }
+
+              return j;
             });
 
           // X
@@ -357,7 +374,7 @@
             bp.chartAreaWidth  = width  - bpMargin.left - bpMargin.right  - bpMargin.gutter;
             bp.chartAreaHeight = height - bpMargin.top  - bpMargin.bottom - bpMargin.gutter;
             bp.chartEachly     = Math.round(bp.chartAreaWidth/lyCount);
-            bp.chartBarHeight  = bp.chartAreaHeight/ticksAll.length;
+            bp.chartBarHeight  = bp.chartAreaHeight/ticksMajor.length;
 
           // Apply the new dimension to chart elements.
```
Which results in:
![screenshot_phenotypes](https://user-images.githubusercontent.com/1566301/28042860-714155b8-658c-11e7-949f-431ec721be87.png)

**Comment by laceysanderson** [comment]
@reynoldtan did this get fixed in the newest Analyzed phenotypes code?

**Comment by reynoldtan** [comment]
**Suggestions:**
1. Add spaces between rows in main page of trait distribution chart where it list genus followed by dataset count. This will clearly define one row from another.
2. Emphasize Trait Distribution Chart link.
3. Use Serif font for Genus (crop) column.
4. Use module's file structure.

Current page:
![current](https://user-images.githubusercontent.com/15472253/37308059-740a65fa-2602-11e8-9985-f07861c8aad5.png)

Proposed page:
![main phenotypes page](https://user-images.githubusercontent.com/15472253/37306761-5da1bba0-25fe-11e8-9741-a0f0a5d3f236.png)

**Issues:**
1. Experiment select field does not filter list of trait options in trait select field.
   It filters the list when selecting a trait not specific to an experiment and 
   clicking Generate Chart (causes An illegal choice has been detected. Please contact the site administrator. error).
![traits not updating](https://user-images.githubusercontent.com/15472253/37306883-bfc9afc2-25fe-11e8-82d1-91e41b54a77b.png)
2. After clicking Generate Chart to generate chart and going back to Select Dataset page, 
   the experiment select field removes other experiments from the options.
![experiments missing](https://user-images.githubusercontent.com/15472253/37306930-e70f0ae6-25fe-11e8-9a52-73a38d25b79e.png)
3. Going back and forth the select dataset and summary chart adds // to the url.
![forward slashes](https://user-images.githubusercontent.com/15472253/37307003-26fe18f4-25ff-11e8-9459-ea6cea86d029.png)
4. In summary chart, select fields are nicely positioned adjacent to one another when character length of options in either fields is short, but causes the fields to stack one on top of another when for example the experiment name is longer than 15-20 characters. Trait select field gets pushed out of the fieldset.

![select field](https://user-images.githubusercontent.com/15472253/37307799-af7f55ba-2601-11e8-93bc-a3d6d0ba2e1f.png)

![summary chart](https://user-images.githubusercontent.com/15472253/37307153-9a712db2-25ff-11e8-95df-675e65ba5a5a.png)

**Comment by laceysanderson** [comment]
## Phenotype Summary Page
I like the addition of the space and the italics for the Genus 👍 
We should also change the "crop" heading to "Genus" to better represent what it is.
I'm not so sure about the "visualize the distribution of values" box as it feels a bit out of place. I think it would be better without the button? Also, perhaps the outline should match the grey used throughout KP? @carolyncaron also suggested perhaps it could mimic a green drupal_set_message()?

## Issues
Thanks for finding these 👍 However you work to fix them, I would like to keep the functionality where the user can start by selecting either trait or experiment and once one is chosen the other is filtered. Also, it is important to allow the drop-downs to be populated via the URL so we can link to this chart already filtered.
### Please make each issue it's own commit to fast-track the review process
