### ISSUE TITLE
Disable Configuration when data has been uploaded.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/analyzedphenotypes#23]
Prevent administrator from altering system variable values (per genus) when data has been uploaded.

**Comment by laceysanderson** [comment]
Note: the current green notice messages regarding this on the configuration form are great but they **should be warnings (i.e. yellow)**...

<img width="946" alt="screen shot 2018-10-04 at 3 25 22 pm" src="https://user-images.githubusercontent.com/1566301/46503973-bbfc9480-c7e9-11e8-917a-cf3d8d36180d.png">

**Comment by laceysanderson** [comment]
Completed. In PR
