### ISSUE TITLE
Trait Distribution Chart Enhancements and Select Fields Not Working.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/analyzedphenotypes#4]
**Enhancements:**
1. Add spaces between rows in main page of trait distribution chart where it list genus followed by dataset count. This will clearly define one row from another.
2. Emphasize Trait Distribution Chart link.
3. Use Serif font for Genus (currently crop) column and change the 'crop' heading to 'Genus'.
4. Use module's file structure.

**Issues:**
1. Experiment select field does not filter list of trait options in trait select field.
   It filters the list when selecting a trait not specific to an experiment and 
   clicking Generate Chart (causes An illegal choice has been detected. Please contact the site administrator. error).
![traits not updating](https://user-images.githubusercontent.com/15472253/37306883-bfc9afc2-25fe-11e8-82d1-91e41b54a77b.png)
2. After clicking Generate Chart to generate chart and going back to Select Dataset page, 
   the experiment select field removes other experiments from the options.
![experiments missing](https://user-images.githubusercontent.com/15472253/37306930-e70f0ae6-25fe-11e8-9a52-73a38d25b79e.png)
3. Going back and forth the select dataset and summary chart adds // to the url.
![forward slashes](https://user-images.githubusercontent.com/15472253/37307003-26fe18f4-25ff-11e8-9459-ea6cea86d029.png)
4. In summary chart, select fields are nicely positioned adjacent to one another when character length of options in either fields is short, but causes the fields to stack one on top of another when for example the experiment name is longer than 15-20 characters. Trait select field gets pushed out of the fieldset.

![select field](https://user-images.githubusercontent.com/15472253/37307799-af7f55ba-2601-11e8-93bc-a3d6d0ba2e1f.png)

![summary chart](https://user-images.githubusercontent.com/15472253/37307153-9a712db2-25ff-11e8-95df-675e65ba5a5a.png)

**Comment by laceysanderson** [comment]
See original issue #2

**Comment by laceysanderson** [comment]
Fixed by PR
