### ISSUE TITLE
Max Allowed Missing Data not affecting result of exported file

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/analyzedphenotypes#54]
![screen shot 2019-01-17 at 10 29 37 am](https://user-images.githubusercontent.com/15472253/51333273-ff021100-1a42-11e9-9b82-54917f802878.png)

Concept was not clear to me that time and it totally slipped off my head 😟 . However, this field has basic js behavior like default value, auto select/highlight value and automatically append % symbol to value entered.

For reference, this was the explanation regarding this field (from specifications).

>Maximum Allowed Missing Data: Enter the percent missing data per germplasm that you would like to allow. For example, a value of 20% will ensure that all germplasm exported have values for at least 20% of site-years this trait was observed in. If you further restrict the site-years exported using other filter criteria, this filter will be applied to the restricted dataset.""

**Comment by laceysanderson** [comment]
Option is no longer available
