### ISSUE TITLE
Phenotype Summary Fields

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/analyzedphenotypes#81]
Implement Tripal 3 fields for quantitative phenotypes summaries that include:
1. Number of Germplasm
2. Number of Locations
3. Number of Values Recorded
4. Number of Experiments
5. Number of Years
6. Number of Traits
![phenotype_summary_placement](https://user-images.githubusercontent.com/15472253/57090431-fff24200-6cc3-11e9-9bf9-782f54c62c54.gif)

**Comment by laceysanderson** [comment]
Merged 🎉
